### PR TITLE
fix: enable multiple integer/float parameters

### LINKED ISSUE #26: [fix] - List of integer/float for a multiple parameter
Cannot give multiple values to an integer/float parameter.

Step to reproduce:

 - create an integer parameter as follows
```
opts = [
        id: :integer_test_values,
        label: "Test integer",
        values: [1, 2, 3, 4],
        multiple: true
      ]
```
- assign the parameter to an arke
- try to create a unit with `integer_test_values`  = [1,2]

The unit should be created because the values are within the opts. Instead it raise an error

### PR DESCRIPTION
**Pull request by ilyichv**
## Description

As per title

## Related Issue

Fixes #26

### CODE REVIEW

File: lib/arke/validator.ex [hunk 1]
```diff
@@ -173,7 +173,7 @@ defmodule Arke.Validator do
     end
   end
 
-  defp parse_value(%{arke_id: :float} = _, value)
+  defp parse_value(%{arke_id: :float, multiple: false} = _, value)
        when not is_number(value) and not is_nil(value) do
```
Comment (ErikFerrari) [inline lib/arke/validator.ex:177]: Maybe only this is needed
```suggestion
       when is_binary(value) do
```

File: lib/arke/validator.ex [hunk 2]
```diff
@@ -164,7 +164,7 @@ defmodule Arke.Validator do
   def get_default_value(parameter, value) when is_nil(value), do: handle_default_value(parameter)
   def get_default_value(parameter, value), do: value
 
-  defp parse_value(%{arke_id: :integer} = _, value)
+  defp parse_value(%{arke_id: :integer, multiple: false} = _, value)
        when not is_integer(value) and not is_nil(value) do
```
Comment (ErikFerrari) [inline lib/arke/validator.ex:168]:
```suggestion
       when is_binary(value) do
```

**Review by ErikFerrari — APPROVED** [review]
